### ISSUE TITLE
No error check when reading from stdin

### ISSUE THREAD

**Issue by bendem** [arcxon/todx#3]
Closing stdin (i.e. using <kbd>ctrl+d</kbd>) is a generally accepted way to close a command line tool relying on interactive input. This is done by checking the [state](http://en.cppreference.com/w/cpp/io/basic_ios/operator_bool) of the stream before/after actually reading from it.

The program currently continously fails to read from stdin once its input gets closed:
![](https://i.imgur.com/IzoGIEa.png)

An example patch is available [here](https://gist.github.com/bendem/34ee061762ead229903896dd81fa738b).

**Comment by bendem** [comment]
https://github.com/arcxon/todx/commit/f0e3325ef7df18c3a75da78feda25c6ecef370f4

**Comment by adiultra** [comment]
Thanks for informing I am too new to app and stuff so I completely didn't know it.

**Comment by bendem** [comment]
Always happy to help :innocent:
